modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/MrUnknown404/ItemFavorites/issues"

[[mods]]
modId="itemfav"
version="1.0.0"
displayName="ItemFavorites"
displayURL="https://github.com/MrUnknown404/ItemFavorites"
#logoFile="examplemod.png"
credits=""
authors="-Unknown-"
description='''
Allows you to favorite items in your inventory
'''

[[dependencies.itemfav]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.itemfav]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"